---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R partials $DEPLOYPATH
    - /bin/cp -R test $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
     - /bin/cp index.html $DEPLOYPATH